name: 'My First GitHub Actions'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Show secret
      shell: bash
      run: |
        echo ${{ secrets.SECRET_1 }}

    - name: Check secret
      shell: pwsh
      run: |
        if ("${{ secrets.SECRET_1 }}" -eq "World") {
            echo "YES!"
        } else {
            echo "NO!"
        }