# # 세가지 파트로 구성됨(name, on, jobs)
# name: 'My First GitHub Actions Workflow'

# # 코드가 push가 되었을 때 작동한다. 이외에도 다양한 작업을 on으로 적용할 수 있다.
# on: push

# env:
#  WORKFLOW_LEVEL: 'This value comes from the work flow level'

# # 실행되면서 무엇을 할지를 아래에 정의한다.
# # 각각의 job은 독립적인 머신에서 이루어지는 것이라고 할 수 있다.
# jobs:
#   first-job:
#     name: 'First Job'
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: 'Set environment variable 1'
#         shell: bash
#         run: |
#           echo "STEP_1 = 'This value comes from the step 1'" >> $GITHUB_ENV
      
#       - name: 'Set environment variable 1'
#         shell: pwsh
#         run: |
#           echo "STEP_2 = 'This value comes from the step 2'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

#       - name: 'Get environment variables'
#         shell: bash
#         run: |
#           echo "WORKFLOW: ${{ env.WORKFLOW_LEVEL }}"
#           echo "STEP 1: ${{ env.STEP_1 }}"
#           echo "STEP 2: ${{ env.STEP_2 }}"
  
#   # job, step 수준에서의 차이
#   # second-job:
#   #   name: 'Second Job'
#   #   runs-on: ubuntu-latest
#   #   env: 
#   #     JOB_LEVEL2: 'This value comes from the job level'
#   #   steps:
#   #     - name: 'Say Hello World on Step 1'
#   #       shell: bash
#   #       env:
#   #         STEP_LEVEL1: 'This value comes from Step 1'
#   #       run:
#   #         echo "Hellow World from Step 1"

#   #         echo "Workflow Level $WORKFLOW_LEVEL"
#   #         echo "Job Level $JOB_LEVEL2"
#   #         echo "Step Level1 $STEP_LEVEL1"
#   #         echo "Step Level2 $STEP_LEVEL2"
      
#   #     - name: 'Say Lorem Ipsum on Step 2'
#   #       shell: pwsh
#   #       env:
#   #         STEP_LEVEL2: 'This value comes from Step 2'
#   #       run: 
#   #         echo "Lorem Ipsum from Step 2"
          
#   #         echo "Workflow Level $env:WORKFLOW_LEVEL"
#   #         echo "Job Level $env:JOB_LEVEL2"
#   #         echo "Step Level1 $env:STEP_LEVEL1"
#   #         echo "Step Level2 $env:STEP_LEVEL2"

name: 'My First GitHub Actions Workflow'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: 'Set output value 1'
      id: step1  
      shell: bash
      run: |
        STEP_1='This value comes from the step 1'

        echo "::add-mask::$STEP_1"
        echo "::set-output name=value1::$STEP_1"

    - name: 'Set output value 2'
      id: step2
      shell: pwsh
      run: |
        $STEP_2='This value comes from the step 2'

        echo "::set-output name=value2::$STEP_2"

    - name: 'Get output values'
      shell: bash
      run: |
        echo "STEP 1: ${{ steps.step1.outputs.value1 }}"
        echo "STEP 2: ${{ steps.step2.outputs.value2 }}"
        echo "SECRET 1: ${{ secrets.SECRET_1 }}"

        if [ ${secrets.SECRET_1} == "secret" ]
          then
            echo "True"
          else
            echo "False"
