# 세가지 파트로 구성됨(name, on, jobs)
name: 'My First GitHub Actions Workflow'

# 코드가 push가 되었을 때 작동한다. 이외에도 다양한 작업을 on으로 적용할 수 있다.
on: push

# 실행되면서 무엇을 할지를 아래에 정의한다.
# 각각의 job은 독립적인 머신에서 이루어지는 것이라고 할 수 있다.
jobs:
  first-job:
    name: 'First Job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Say Hello World on Step 1'
        shell: bash
        run:
          echo "Hellow World from Step 1"
      
      - name: 'Say Lorem Ipsum on Step 2'
        shell: pwsh
        run: 
          echo "Lorem Ipsum from Step 2"

  # second-job:
  #   name: ''